In [1]:
import pandas as pd

In [11]:
data = [100, 102, 104]
series = pd.Series(data, index = ['a','b','c'])
series.loc['c'] = 200   # iloc for int location and loc for location label
print(series[series<200])

a    100
b    102
dtype: int64

In [12]:
calories = {"Day 1": 1750, "Day 2": 530, "Day 3": 850} #no labeling of indexing required in dictionary
series = pd.Series(calories)
series

Day 1    1750
Day 2     530
Day 3     850
dtype: int64

In [17]:

series.loc["Day 3"]

np.int64(1550)

In [19]:
series[series>=1000]

Day 1    1750
Day 3    1550
dtype: int64

In [21]:
data = {"Name":["Luffy", "Zoro", "Nami"],
        "Bounty": [5000, 4000, 3000]
       }

df = pd.DataFrame(data, index = ['Pirate 1', 'Pirate 2', 'Pirate 3'])
print(df)

           Name  Bounty
Pirate 1  Luffy    5000
Pirate 2   Zoro    4000
Pirate 3   Nami    3000

In [23]:
df.loc['Pirate 2']

Name      Zoro
Bounty    4000
Name: Pirate 2, dtype: object

In [26]:
df.iloc[2]

Name      Nami
Bounty    3000
Name: Pirate 3, dtype: object

In [27]:
df

           Name  Bounty
Pirate 1  Luffy    5000
Pirate 2   Zoro    4000
Pirate 3   Nami    3000

In [29]:
#new column
df["Title"] = ["Captain", "Swordsman", "Navigator"]
df

           Name  Bounty      Title
Pirate 1  Luffy    5000    Captain
Pirate 2   Zoro    4000  Swordsman
Pirate 3   Nami    3000  Navigator

In [37]:
#adds new row
new_rows = pd.DataFrame([{"Name": "Sanji", "Bounty": 4000, "Title": "Cook"}], index = ['Pirate 4'])
df = pd.concat([df,new_rows])
df

           Name  Bounty      Title
Pirate 1  Luffy    5000    Captain
Pirate 2   Zoro    4000  Swordsman
Pirate 3   Nami    3000  Navigator
0         Sanji    4000       Cook
0         Sanji    4000       Cook
0         Sanji    4000       Cook
Pirate 4  Sanji    4000       Cook

In [41]:
df = df.drop(0) #drops rows with index 0, 0 is the index name
df

           Name  Bounty      Title
Pirate 1  Luffy    5000    Captain
Pirate 2   Zoro    4000  Swordsman
Pirate 3   Nami    3000  Navigator
Pirate 4  Sanji    4000       Cook

In [52]:
df = pd.read_csv("Pokemon.csv", index_col = "Name")
df

             No    Type1   Type2  Height  Weight  Legendary
Name
Bulbasaur     1    Grass  Poison     0.7     6.9          0
Ivysaur       2    Grass  Poison     1.0    13.0          0
Venusaur      3    Grass  Poison     2.0   100.0          0
Charmander    4     Fire     NaN     0.6     8.5          0
Charmeleon    5     Fire     NaN     1.1    19.0          0
...         ...      ...     ...     ...     ...        ...
Moltres     146     Fire  Flying     2.0    60.0          1
Dratini     147   Dragon     NaN     1.8     3.3          0
Dragonair   148   Dragon     NaN     4.0    16.5          0
Dragonite   149   Dragon  Flying     2.2   210.0          0
Mewtwo      150  Psychic     NaN     2.0   122.0          1

[150 rows x 6 columns]

In [44]:
# df.to_string() #provides entire info

"      No        Name     Type1     Type2  Height  Weight  Legendary\n0      1   Bulbasaur     Grass    Poison     0.7     6.9          0\n1      2     Ivysaur     Grass    Poison     1.0    13.0          0\n2      3    Venusaur     Grass    Poison     2.0   100.0          0\n3      4  Charmander      Fire       NaN     0.6     8.5          0\n4      5  Charmeleon      Fire       NaN     1.1    19.0          0\n5      6   Charizard      Fire    Flying     1.7    90.5          0\n6      7    Squirtle     Water       NaN     0.5     9.0          0\n7      8   Wartortle     Water       NaN     1.0    22.5          0\n8      9   Blastoise     Water       NaN     1.6    85.5          0\n9     10    Caterpie       Bug       NaN     0.3     2.9          0\n10    11     Metapod       Bug       NaN     0.7     9.9          0\n11    12  Butterfree       Bug    Flying     1.1    32.0          0\n12    13      Weedle       Bug    Poison     0.3     3.2          0\n13    14      Kakuna       Bug    Poison     0.6    10.0          0\n14    15    Beedrill       Bug    Poison     1.0    29.5          0\n15    16      Pidgey    Normal    Flying     0.3     1.8          0\n16    17   Pidgeotto    Normal    Flying     1.1    30.0          0\n17    18     Pidgeot    Normal    Flying     1.5    39.5          0\n18    19     Rattata    Normal       NaN     0.3     3.5          0\n19    20    Raticate    Normal       NaN     0.7    18.5          0\n20    21     Spearow    Normal    Flying     0.3     2.0          0\n21    22      Fearow    Normal    Flying     1.2    38.0          0\n22    23       Ekans    Poison       NaN     2.0     6.9          0\n23    24       Arbok    Poison       NaN     3.5    65.0          0\n24    25     Pikachu  Electric       NaN     0.4     6.0          0\n25    26      Raichu  Electric       NaN     0.8    30.0          0\n26    27   Sandshrew    Ground       NaN     0.6    12.0          0\n27    28   Sandslash    Ground       NaN     1.0    29.5          0\n28    29    Nidoran♀    Poison       NaN     0.4     7.0          0\n29    30    Nidorina    Poison       NaN     0.8    20.0          0\n30    31   Nidoqueen    Poison    Ground     1.3    60.0          0\n31    32    Nidoran♂    Poison       NaN     0.5     9.0          0\n32    33    Nidorino    Poison       NaN     0.9    19.5          0\n33    34    Nidoking    Poison    Ground     1.4    62.0          0\n34    35    Clefairy     Fairy       NaN     0.6     7.5          0\n35    36    Clefable     Fairy       NaN     1.3    40.0          0\n36    37      Vulpix      Fire       NaN     0.6     9.9          0\n37    38   Ninetales      Fire       NaN     1.1    19.9          0\n38    39  Jigglypuff    Normal     Fairy     0.5     5.5          0\n39    40  Wigglytuff    Normal     Fairy     1.0    12.0          0\n40    41       Zubat    Poison    Flying     0.8     7.5          0\n41    42      Golbat    Poison    Flying     1.6    55.0          0\n42    43      Oddish     Grass    Poison     0.5     5.4          0\n43    44       Gloom     Grass    Poison     0.8     8.6          0\n44    45   Vileplume     Grass    Poison     1.2    18.6          0\n45    46       Paras       Bug     Grass     0.3     5.4          0\n46    47    Parasect       Bug     Grass     1.0    29.5          0\n47    48     Venonat       Bug    Poison     1.0    30.0          0\n48    49    Venomoth       Bug    Poison     1.5    12.5          0\n49    50     Diglett    Ground       NaN     0.2     0.8          0\n50    51     Dugtrio    Ground       NaN     0.7    33.3          0\n51    52      Meowth    Normal       NaN     0.4     4.2          0\n52    53     Persian    Normal       NaN     1.0    32.0          0\n53    54     Psyduck     Water       NaN     0.8    19.6          0\n54    55     Golduck     Water       NaN     1.7    76.6          0\n55    56      Mankey  Fighting       NaN     0.5    28.0          0\n56    57    Primeape  Fighting       NaN     1.0    32.0          0\n57    58   Growlithe      Fire       NaN     0.7    19.0          0\n58    59    Arcanine      Fire       NaN     1.9   155.0          0\n59    60     Poliwag     Water       NaN     0.6    12.4          0\n60    61   Poliwhirl     Water       NaN     1.0    20.0          0\n61    62   Poliwrath     Water  Fighting     1.3    54.0          0\n62    63        Abra   Psychic       NaN     0.9    19.5          0\n63    64     Kadabra   Psychic       NaN     1.3    56.5          0\n64    65    Alakazam   Psychic       NaN     1.5    48.0          0\n65    66      Machop  Fighting       NaN     0.8    19.5          0\n66    67     Machoke  Fighting       NaN     1.5    70.5          0\n67    68     Machamp  Fighting       NaN     1.6   130.0          0\n68    69  Bellsprout     Grass    Poison     0.7     4.0          0\n69    70  Weepinbell     Grass    Poison     1.0     6.4          0\n70    71  Victreebel     Grass    Poison     1.7    15.5          0\n71    72   Tentacool     Water    Poison     0.9    45.5          0\n72    73  Tentacruel     Water    Poison     1.6    55.0          0\n73    74     Geodude      Rock    Ground     0.4    20.0          0\n74    75    Graveler      Rock    Ground     1.0   105.0          0\n75    76       Golem      Rock    Ground     1.4   300.0          0\n76    77      Ponyta      Fire       NaN     1.0    30.0          0\n77    78    Rapidash      Fire       NaN     1.7    95.0          0\n78    79    Slowpoke     Water   Psychic     1.2    36.0          0\n79    80     Slowbro     Water   Psychic     1.6    78.5          0\n80    81   Magnemite  Electric     Steel     0.3     6.0          0\n81    82    Magneton  Electric     Steel     1.0    60.0          0\n82    83  Farfetch'd    Normal    Flying     0.8    15.0          0\n83    84       Doduo    Normal    Flying     1.4    39.2          0\n84    85      Dodrio    Normal    Flying     1.8    85.2          0\n85    86        Seel     Water       NaN     1.1    90.0          0\n86    87     Dewgong     Water       Ice     1.7   120.0          0\n87    88      Grimer    Poison       NaN     0.9    30.0          0\n88    89         Muk    Poison       NaN     1.2    30.0          0\n89    90    Shellder     Water       NaN     0.3     4.0          0\n90    91    Cloyster     Water       Ice     1.5   132.5          0\n91    92      Gastly     Ghost    Poison     1.3     0.1          0\n92    93     Haunter     Ghost    Poison     1.6     0.1          0\n93    94      Gengar     Ghost    Poison     1.5    40.5          0\n94    95        Onix      Rock    Ground     8.8   210.0          0\n95    96     Drowzee   Psychic       NaN     1.0    32.4          0\n96    97       Hypno   Psychic       NaN     1.6    75.6          0\n97    98      Krabby     Water       NaN     0.4     6.5          0\n98    99     Kingler     Water       NaN     1.3    60.0          0\n99   100     Voltorb  Electric       NaN     0.5    10.4          0\n100  101   Electrode  Electric       NaN     1.2    66.6          0\n101  102   Exeggcute     Grass   Psychic     0.4     2.5          0\n102  103   Exeggutor     Grass   Psychic     2.0   120.0          0\n103  104      Cubone    Ground       NaN     0.4     6.5          0\n104  105     Marowak    Ground       NaN     1.0    45.0          0\n105  106   Hitmonlee  Fighting       NaN     1.5    49.8          0\n106  107  Hitmonchan  Fighting       NaN     1.4    50.2          0\n107  108   Lickitung    Normal       NaN     1.2    65.5          0\n108  109     Koffing    Poison       NaN     0.6     1.0          0\n109  110     Weezing    Poison       NaN     1.2     9.5          0\n110  111     Rhyhorn    Ground      Rock     1.0   115.0          0\n111  112      Rhydon    Ground      Rock     1.9   120.0          0\n112  113     Chansey    Normal       NaN     1.1    34.6          0\n113  114     Tangela     Grass       NaN     1.0    35.0          0\n114  115  Kangaskhan    Normal       NaN     2.2    80.0          0\n115  116      Horsea     Water       NaN     0.4     8.0          0\n116  117      Seadra     Water       NaN     1.2    25.0          0\n117  118     Goldeen     Water       NaN     0.6    15.0          0\n118  119     Seaking     Water       NaN     1.3    39.0          0\n119  120      Staryu     Water       NaN     0.8    34.5          0\n120  121     Starmie     Water   Psychic     1.1    80.0          0\n121  122    Mr. Mime   Psychic     Fairy     1.3    54.5          0\n122  123     Scyther       Bug    Flying     1.5    56.0          0\n123  124        Jynx       Ice   Psychic     1.4    40.6          0\n124  125  Electabuzz  Electric       NaN     1.1    30.0          0\n125  126      Magmar      Fire       NaN     1.3    44.5          0\n126  127      Pinsir       Bug       NaN     1.5    55.0          0\n127  128      Tauros    Normal       NaN     1.4    88.4          0\n128  129    Magikarp     Water       NaN     0.9    10.0          0\n129  130    Gyarados     Water    Flying     6.5   235.0          0\n130  131      Lapras     Water       Ice     2.5   220.0          0\n131  132       Ditto    Normal       NaN     0.3     4.0          0\n132  133       Eevee    Normal       NaN     0.3     6.5          0\n133  134    Vaporeon     Water       NaN     1.0    29.0          0\n134  135     Jolteon  Electric       NaN     0.8    24.5          0\n135  136     Flareon      Fire       NaN     0.9    25.0          0\n136  137     Porygon    Normal       NaN     0.8    36.5          0\n137  138     Omanyte      Rock     Water     0.4     7.5          0\n138  139     Omastar      Rock     Water     1.0    35.0          0\n139  140      Kabuto      Rock     Water     0.5    11.5          0\n140  141    Kabutops      Rock     Water     1.3    40.5          0\n141  142  Aerodactyl      Rock    Flying     1.8    59.0          0\n142  143     Snorlax    Normal       NaN     2.1   460.0          0\n143  144    Articuno       Ice    Flying     1.7    55.4          1\n144  145      Zapdos  Electric    Flying     1.6    52.6          1\n145  146     Moltres      Fire    Flying     2.0    60.0          1\n146  147     Dratini    Dragon       NaN     1.8     3.3          0\n147  148   Dragonair    Dragon       NaN     4.0    16.5          0\n148  149   Dragonite    Dragon    Flying     2.2   210.0          0\n149  150      Mewtwo   Psychic       NaN     2.0   122.0          1"

In [45]:
#Selection by column
df["Name"]

0       Bulbasaur
1         Ivysaur
2        Venusaur
3      Charmander
4      Charmeleon
          ...
145       Moltres
146       Dratini
147     Dragonair
148     Dragonite
149        Mewtwo
Name: Name, Length: 150, dtype: object

In [49]:
df[["Weight", "Height"]]

     Weight  Height
0       6.9     0.7
1      13.0     1.0
2     100.0     2.0
3       8.5     0.6
4      19.0     1.1
..      ...     ...
145    60.0     2.0
146     3.3     1.8
147    16.5     4.0
148   210.0     2.2
149   122.0     2.0

[150 rows x 2 columns]

In [50]:
df[[]]#Selection by Rows
df

      No        Name    Type1   Type2  Height  Weight  Legendary
0      1   Bulbasaur    Grass  Poison     0.7     6.9          0
1      2     Ivysaur    Grass  Poison     1.0    13.0          0
2      3    Venusaur    Grass  Poison     2.0   100.0          0
3      4  Charmander     Fire     NaN     0.6     8.5          0
4      5  Charmeleon     Fire     NaN     1.1    19.0          0
..   ...         ...      ...     ...     ...     ...        ...
145  146     Moltres     Fire  Flying     2.0    60.0          1
146  147     Dratini   Dragon     NaN     1.8     3.3          0
147  148   Dragonair   Dragon     NaN     4.0    16.5          0
148  149   Dragonite   Dragon  Flying     2.2   210.0          0
149  150      Mewtwo  Psychic     NaN     2.0   122.0          1

[150 rows x 7 columns]

In [51]:
df.loc[0]

No                   1
Name         Bulbasaur
Type1            Grass
Type2           Poison
Height             0.7
Weight             6.9
Legendary            0
Name: 0, dtype: object

In [53]:
df

             No    Type1   Type2  Height  Weight  Legendary
Name
Bulbasaur     1    Grass  Poison     0.7     6.9          0
Ivysaur       2    Grass  Poison     1.0    13.0          0
Venusaur      3    Grass  Poison     2.0   100.0          0
Charmander    4     Fire     NaN     0.6     8.5          0
Charmeleon    5     Fire     NaN     1.1    19.0          0
...         ...      ...     ...     ...     ...        ...
Moltres     146     Fire  Flying     2.0    60.0          1
Dratini     147   Dragon     NaN     1.8     3.3          0
Dragonair   148   Dragon     NaN     4.0    16.5          0
Dragonite   149   Dragon  Flying     2.2   210.0          0
Mewtwo      150  Psychic     NaN     2.0   122.0          1

[150 rows x 6 columns]

In [56]:
df.loc["Charizard", ["Height", "Weight"]]

Height     1.7
Weight    90.5
Name: Charizard, dtype: object

In [57]:
df.iloc[0:16]

            No   Type1   Type2  Height  Weight  Legendary
Name
Bulbasaur    1   Grass  Poison     0.7     6.9          0
Ivysaur      2   Grass  Poison     1.0    13.0          0
Venusaur     3   Grass  Poison     2.0   100.0          0
Charmander   4    Fire     NaN     0.6     8.5          0
Charmeleon   5    Fire     NaN     1.1    19.0          0
Charizard    6    Fire  Flying     1.7    90.5          0
Squirtle     7   Water     NaN     0.5     9.0          0
Wartortle    8   Water     NaN     1.0    22.5          0
Blastoise    9   Water     NaN     1.6    85.5          0
Caterpie    10     Bug     NaN     0.3     2.9          0
Metapod     11     Bug     NaN     0.7     9.9          0
Butterfree  12     Bug  Flying     1.1    32.0          0
Weedle      13     Bug  Poison     0.3     3.2          0
Kakuna      14     Bug  Poison     0.6    10.0          0
Beedrill    15     Bug  Poison     1.0    29.5          0
Pidgey      16  Normal  Flying     0.3     1.8          0

In [58]:
df.iloc[0:16:2, 0:3]   #[row1:rown:jump, col1:coln]

            No  Type1   Type2
Name
Bulbasaur    1  Grass  Poison
Venusaur     3  Grass  Poison
Charmeleon   5   Fire     NaN
Squirtle     7  Water     NaN
Blastoise    9  Water     NaN
Metapod     11    Bug     NaN
Weedle      13    Bug  Poison
Beedrill    15    Bug  Poison

In [64]:
pokemon = input("Enter a Pokemon name: ")
try:
    print(df.loc[pokemon])
except KeyError:
    print(f"{pokemon} not found")

Enter a Pokemon name:  ujhuih

ujhuih not found

In [65]:
df

             No    Type1   Type2  Height  Weight  Legendary
Name
Bulbasaur     1    Grass  Poison     0.7     6.9          0
Ivysaur       2    Grass  Poison     1.0    13.0          0
Venusaur      3    Grass  Poison     2.0   100.0          0
Charmander    4     Fire     NaN     0.6     8.5          0
Charmeleon    5     Fire     NaN     1.1    19.0          0
...         ...      ...     ...     ...     ...        ...
Moltres     146     Fire  Flying     2.0    60.0          1
Dratini     147   Dragon     NaN     1.8     3.3          0
Dragonair   148   Dragon     NaN     4.0    16.5          0
Dragonite   149   Dragon  Flying     2.2   210.0          0
Mewtwo      150  Psychic     NaN     2.0   122.0          1

[150 rows x 6 columns]

In [66]:
df.mean(numeric_only=True)

No           75.500000
Height        1.200000
Weight       46.231333
Legendary     0.026667
dtype: float64

In [67]:
df.sum(numeric_only=True)

No           11325.0
Height         180.0
Weight        6934.7
Legendary        4.0
dtype: float64

In [68]:
df.max(numeric_only=True)

No           150.0
Height         8.8
Weight       460.0
Legendary      1.0
dtype: float64

In [69]:
df.count()

No           150
Type1        150
Type2         67
Height       150
Weight       150
Legendary    150
dtype: int64

In [71]:
# mean(), min(), max(),sum(), count() are aggregate functions applicable to whole database


#Single Column
df["Height"].mean()

np.float64(1.2)

In [72]:
df["Height"].sum()

np.float64(180.0)

In [73]:
df["Height"].min()

np.float64(0.2)

In [74]:
group = df.groupby("Type1")
group

In [75]:
group.mean(numeric_only = True)

                  No    Height     Weight  Legendary
Type1
Bug        42.916667  0.900000  22.991667   0.000000
Dragon    148.000000  2.666667  76.600000   0.000000
Electric   91.111111  0.855556  31.788889   0.111111
Fairy      35.500000  0.950000  23.750000   0.000000
Fighting   75.285714  1.185714  54.285714   0.000000
Fire       64.166667  1.216667  48.025000   0.083333
Ghost      93.000000  1.466667  13.566667   0.000000
Grass      55.583333  1.083333  27.991667   0.000000
Ground     73.500000  0.850000  45.262500   0.000000
Ice       134.000000  1.550000  48.000000   0.500000
Normal     71.727273  0.986364  50.086364   0.000000
Poison     51.071429  1.221429  27.314286   0.000000
Psychic    93.857143  1.371429  58.357143   0.142857
Rock      113.333333  1.844444  87.611111   0.000000
Water      85.928571  1.300000  57.967857   0.000000

In [76]:
group[["Height","Weight"]].mean()

            Height     Weight
Type1
Bug       0.900000  22.991667
Dragon    2.666667  76.600000
Electric  0.855556  31.788889
Fairy     0.950000  23.750000
Fighting  1.185714  54.285714
Fire      1.216667  48.025000
Ghost     1.466667  13.566667
Grass     1.083333  27.991667
Ground    0.850000  45.262500
Ice       1.550000  48.000000
Normal    0.986364  50.086364
Poison    1.221429  27.314286
Psychic   1.371429  58.357143
Rock      1.844444  87.611111
Water     1.300000  57.967857

In [77]:
group[["Height","Weight"]].min()

          Height  Weight
Type1
Bug          0.3     2.9
Dragon       1.8     3.3
Electric     0.3     6.0
Fairy        0.6     7.5
Fighting     0.5    19.5
Fire         0.6     8.5
Ghost        1.3     0.1
Grass        0.4     2.5
Ground       0.2     0.8
Ice          1.4    40.6
Normal       0.3     1.8
Poison       0.4     1.0
Psychic      0.9    19.5
Rock         0.4     7.5
Water        0.3     4.0

In [78]:
df

             No    Type1   Type2  Height  Weight  Legendary
Name
Bulbasaur     1    Grass  Poison     0.7     6.9          0
Ivysaur       2    Grass  Poison     1.0    13.0          0
Venusaur      3    Grass  Poison     2.0   100.0          0
Charmander    4     Fire     NaN     0.6     8.5          0
Charmeleon    5     Fire     NaN     1.1    19.0          0
...         ...      ...     ...     ...     ...        ...
Moltres     146     Fire  Flying     2.0    60.0          1
Dratini     147   Dragon     NaN     1.8     3.3          0
Dragonair   148   Dragon     NaN     4.0    16.5          0
Dragonite   149   Dragon  Flying     2.2   210.0          0
Mewtwo      150  Psychic     NaN     2.0   122.0          1

[150 rows x 6 columns]

In [88]:
#Drop irrelevant columns
df = df.drop(columns = ["Legendary", "No"])

KeyError: "['Legendary', 'No'] not found in axis"

In [87]:
df1

NameError: name 'df1' is not defined

In [82]:
#Handle missing data
df = df.dropna(subset=["Type2"])  #dropna ---->>> drop not available values

In [84]:
df

               Type1   Type2  Height  Weight
Name
Bulbasaur      Grass  Poison     0.7     6.9
Ivysaur        Grass  Poison     1.0    13.0
Venusaur       Grass  Poison     2.0   100.0
Charizard       Fire  Flying     1.7    90.5
Butterfree       Bug  Flying     1.1    32.0
...              ...     ...     ...     ...
Aerodactyl      Rock  Flying     1.8    59.0
Articuno         Ice  Flying     1.7    55.4
Zapdos      Electric  Flying     1.6    52.6
Moltres         Fire  Flying     2.0    60.0
Dragonite     Dragon  Flying     2.2   210.0

[67 rows x 4 columns]

In [85]:
df.fillna({"Type2": "None"})
df

               Type1   Type2  Height  Weight
Name
Bulbasaur      Grass  Poison     0.7     6.9
Ivysaur        Grass  Poison     1.0    13.0
Venusaur       Grass  Poison     2.0   100.0
Charizard       Fire  Flying     1.7    90.5
Butterfree       Bug  Flying     1.1    32.0
...              ...     ...     ...     ...
Aerodactyl      Rock  Flying     1.8    59.0
Articuno         Ice  Flying     1.7    55.4
Zapdos      Electric  Flying     1.6    52.6
Moltres         Fire  Flying     2.0    60.0
Dragonite     Dragon  Flying     2.2   210.0

[67 rows x 4 columns]

In [89]:
df

               Type1   Type2  Height  Weight
Name
Bulbasaur      Grass  Poison     0.7     6.9
Ivysaur        Grass  Poison     1.0    13.0
Venusaur       Grass  Poison     2.0   100.0
Charizard       Fire  Flying     1.7    90.5
Butterfree       Bug  Flying     1.1    32.0
...              ...     ...     ...     ...
Aerodactyl      Rock  Flying     1.8    59.0
Articuno         Ice  Flying     1.7    55.4
Zapdos      Electric  Flying     1.6    52.6
Moltres         Fire  Flying     2.0    60.0
Dragonite     Dragon  Flying     2.2   210.0

[67 rows x 4 columns]